import type { Repository } from '@/lib/types';

export const mockRepositories: Repository[] = [
  {
    id: 1,
    name: 'react',
    full_name: 'facebook/react',
    owner: {
      login: 'facebook',
      id: 69631,
      avatar_url: 'https://avatars.githubusercontent.com/u/69631?v=4',
      html_url: 'https://github.com/facebook',
    },
    html_url: 'https://github.com/facebook/react',
    description: 'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
    stargazers_count: 220000,
    watchers_count: 220000,
    forks_count: 45000,
    open_issues_count: 1100,
    language: 'JavaScript',
    created_at: '2013-05-29T20:49:29Z',
    updated_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    license: { key: 'mit', name: 'MIT License', spdx_id: 'MIT', url: 'https://api.github.com/licenses/mit', node_id: 'MDc6TGljZW5zZTEz' },
    size: 150000,
    topics: ['javascript', 'library', 'ui', 'frontend'],
  },
  {
    id: 2,
    name: 'tensorflow',
    full_name: 'tensorflow/tensorflow',
    owner: {
      login: 'tensorflow',
      id: 15658638,
      avatar_url: 'https://avatars.githubusercontent.com/u/15658638?v=4',
      html_url: 'https://github.com/tensorflow',
    },
    html_url: 'https://github.com/tensorflow/tensorflow',
    description: 'An Open Source Machine Learning Framework for Everyone',
    stargazers_count: 180000,
    watchers_count: 180000,
    forks_count: 85000,
    open_issues_count: 2500,
    language: 'C++',
    created_at: '2015-11-07T01:19:20Z',
    updated_at: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    pushed_at: new Date(new Date().setDate(new Date().getDate() - 1)).toISOString(),
    license: { key: 'apache-2.0', name: 'Apache License 2.0', spdx_id: 'Apache-2.0', url: 'https://api.github.com/licenses/apache-2.0', node_id: 'MDc6TGljZW5zZTI=' },
    size: 500000,
    topics: ['machine-learning', 'deep-learning', 'python', 'neural-network'],
  },
  {
    id: 3,
    name: 'vscode',
    full_name: 'microsoft/vscode',
    owner: {
      login: 'microsoft',
      id: 6154722,
      avatar_url: 'https://avatars.githubusercontent.com/u/6154722?v=4',
      html_url: 'https://github.com/microsoft',
    },
    html_url: 'https://github.com/microsoft/vscode',
    description: 'Visual Studio Code',
    stargazers_count: 155000,
    watchers_count: 155000,
    forks_count: 27000,
    open_issues_count: 6000,
    language: 'TypeScript',
    created_at: '2015-09-03T20:23:38Z',
    updated_at: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    pushed_at: new Date(new Date().setDate(new Date().getDate() - 2)).toISOString(),
    license: { key: 'mit', name: 'MIT License', spdx_id: 'MIT', url: 'https://api.github.com/licenses/mit', node_id: 'MDc6TGljZW5zZTEz' },
    size: 800000,
    topics: ['editor', 'typescript', 'electron'],
  },
  {
    id: 4,
    name: 'next.js',
    full_name: 'vercel/next.js',
    owner: {
      login: 'vercel',
      id: 14985020,
      avatar_url: 'https://avatars.githubusercontent.com/u/14985020?v=4',
      html_url: 'https://github.com/vercel',
    },
    html_url: 'https://github.com/vercel/next.js',
    description: 'The React Framework',
    stargazers_count: 115000,
    watchers_count: 115000,
    forks_count: 25000,
    open_issues_count: 1500,
    language: 'JavaScript',
    created_at: '2016-10-25T14:18:28Z',
    updated_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    license: { key: 'mit', name: 'MIT License', spdx_id: 'MIT', url: 'https://api.github.com/licenses/mit', node_id: 'MDc6TGljZW5zZTEz' },
    size: 250000,
    topics: ['react', 'framework', 'ssr', 'pwa'],
  },
    {
    id: 5,
    name: 'rust',
    full_name: 'rust-lang/rust',
    owner: {
      login: 'rust-lang',
      id: 5430905,
      avatar_url: 'https://avatars.githubusercontent.com/u/5430905?v=4',
      html_url: 'https://github.com/rust-lang',
    },
    html_url: 'https://github.com/rust-lang/rust',
    description: 'Empowering everyone to build reliable and efficient software.',
    stargazers_count: 89000,
    watchers_count: 89000,
    forks_count: 11500,
    open_issues_count: 8000,
    language: 'Rust',
    created_at: '2010-07-08T22:45:53Z',
    updated_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    license: { key: 'mit', name: 'MIT License', spdx_id: 'MIT', url: 'https://api.github.com/licenses/mit', node_id: 'MDc6TGljZW5zZTEz' },
    size: 700000,
    topics: ['compiler', 'language', 'systems', 'rust'],
  },
  {
    id: 6,
    name: 'go',
    full_name: 'golang/go',
    owner: {
      login: 'golang',
      id: 4314092,
      avatar_url: 'https://avatars.githubusercontent.com/u/4314092?v=4',
      html_url: 'https://github.com/golang',
    },
    html_url: 'https://github.com/golang/go',
    description: 'The Go programming language',
    stargazers_count: 118000,
    watchers_count: 118000,
    forks_count: 16000,
    open_issues_count: 7500,
    language: 'Go',
    created_at: '2014-08-14T04:22:24Z',
    updated_at: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    pushed_at: new Date(new Date().setDate(new Date().getDate() - 3)).toISOString(),
    license: { key: 'bsd-3-clause', name: 'BSD 3-Clause "New" or "Revised" License', spdx_id: 'BSD-3-Clause', url: 'https://api.github.com/licenses/bsd-3-clause', node_id: 'MDc6TGljZW5zZTU=' },
    size: 600000,
    topics: ['go', 'language', 'compiler', 'programming-language'],
  },
];
